
package main

import(
"fmt"
)

// represent a single Sequence
type Seq struct {
	Name     string
	Sequence string
}

type Fasta []Seq

func main() {
	test1 :=  Fasta{Seq{Name: "SAC1",
		Sequence: "TGCATGTTGGAAACATGGCCCTGGCATATGTCTATCTTTCTCTCGGTCTCTAGGGCTAAGCTTCTCTTCCTTATATTTTT"},
		Seq{Name: "SAC2",
			Sequence: "TGCATTACTTAGAGTGGTAGGTCAGTAGGGACGGTGCCTAACGTGTGAATCTCAAATGACACACAATTCCTTAAACATAGTACACGTC"},
		Seq{Name: "SAC3",
			Sequence: "TGCATAAGGCTACCATCTAGGCGAACGTTATATTGGAATGGAATATGCAAGATCGGAAGAGCGGTTCAGCAGGACCGAGACC"},
		Seq{Name: "SAC4",
			Sequence: "TGCATTAGGGGTGTGTGTGTGTGTGTGTGTGTGTGTTTGGTATGCAAGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCATC"},
		Seq{Name: "SAC5",
			Sequence: "TGCATGCTTTTCAGATTTTATTTTGTGTGGATCCCCATTGAGGCCTTTCCTCGCGTTCATCAGAAATGTATAGAGATGGCTTCCA"},
		Seq{Name: "SAC6",
			Sequence: "TGCATTGATGCTAAATAGGGCCTCAGCTTGACAATTCATTCAAGTAACAAATGTTTGGATTCCTGATTTTGATTTTTTTTTCTTAACATTT"},
		Seq{Name: "SAC7",
			Sequence: "TGCATTCCTACTTGGACACGTTACAGTAGATGTAACAACCCACTTTGTAAGCCTCATACTACCGACATGCGTAATTAGAAAAAGAGAGAGTTAAG"},
		Seq{Name: "SAC8",
			Sequence: "TGCATGATTTTTCACCAGTACTTGAAAATGTGAATAAAACCGTAAATACGTTACGCTCCATACATGCAAGATCGGAAGAGCGGTT"},
		Seq{Name: "SAC9",
			Sequence: "TGCATGTGTGTATACATATCTGTACTGTCTCGCTTGACAGGCTTACAGTGGCACTGGGAATGATACTTATGCCTGTAATGTGTTT"},
		Seq{Name: "SAC10",
			Sequence: "TGCATTTAATCTTATCCGATAGGCGAAATCTAAATAGATAACTTTGGAAAAACTGGGCCCAGAGGCTTACTGAGGATTAAACTAC"},
	}

	
	fmt.Println(test1)

}
