package fasta

import (
	"fmt"
	"reflect"
	"testing"
)

/*
The unit tests are broken down into test functions which correspond to the
package file names.
*/

func TestIO(t *testing.T) {

	test_1 := Fasta{[]Seq{Seq{name: "SAC1",
		sequence: "TGCATGTTGGAAACATGGCCCTGGCATATGTCTATCTTTCTCTCGGTCTCTAGGGCTAAGCTTCTCTTCCTTATATTTTT"},
		Seq{name: "SAC2",
			sequence: "TGCATTACTTAGAGTGGTAGGTCAGTAGGGACGGTGCCTAACGTGTGAATCTCAAATGACACACAATTCCTTAAACATAGTACACGTC"},
		Seq{name: "SAC3",
			sequence: "TGCATAAGGCTACCATCTAGGCGAACGTTATATTGGAATGGAATATGCAAGATCGGAAGAGCGGTTCAGCAGGACCGAGACC"},
		Seq{name: "SAC4",
			sequence: "TGCATTAGGGGTGTGTGTGTGTGTGTGTGTGTGTGTTTGGTATGCAAGATCGGAAGAGCGGTTCAGCAGGAATGCCGAGACCATC"},
		Seq{name: "SAC5",
			sequence: "TGCATGCTTTTCAGATTTTATTTTGTGTGGATCCCCATTGAGGCCTTTCCTCGCGTTCATCAGAAATGTATAGAGATGGCTTCCA"},
		Seq{name: "SAC6",
			sequence: "TGCATTGATGCTAAATAGGGCCTCAGCTTGACAATTCATTCAAGTAACAAATGTTTGGATTCCTGATTTTGATTTTTTTTTCTTAACATTT"},
		Seq{name: "SAC7",
			sequence: "TGCATTCCTACTTGGACACGTTACAGTAGATGTAACAACCCACTTTGTAAGCCTCATACTACCGACATGCGTAATTAGAAAAAGAGAGAGTTAAG"},
		Seq{name: "SAC8",
			sequence: "TGCATGATTTTTCACCAGTACTTGAAAATGTGAATAAAACCGTAAATACGTTACGCTCCATACATGCAAGATCGGAAGAGCGGTT"},
		Seq{name: "SAC9",
			sequence: "TGCATGTGTGTATACATATCTGTACTGTCTCGCTTGACAGGCTTACAGTGGCACTGGGAATGATACTTATGCCTGTAATGTGTTT"},
		Seq{name: "SAC10",
			sequence: "TGCATTTAATCTTATCCGATAGGCGAAATCTAAATAGATAACTTTGGAAAAACTGGGCCCAGAGGCTTACTGAGGATTAAACTAC"},
	}}

	ex_file := "../example_data/example1.fasta"

	test_in := Read(ex_file)

	if reflect.DeepEqual(test_1, test_in) != true {
		t.Errorf("Test of fasta reader produced incorrect data. Received: %v\n", test_in)
	}
}

func TestQuery(t *testing.T) {

	AF298042 := Fasta{[]Seq{Seq{name: "AF298042.1 Salvelinus alpinus alpinus haplotype ARCTIC_16 mitochondrial D-loop, partial sequence",
		sequence: "CCACTAATATGTACAATAATGAATATTGTATCTCAACAAATTAGTGTCATAATACATCTATGTATAATATTGCATATTATGTATTTACCCATATATACAATACCTGTATGATGAGTAGTACATCATATGTATTATCAACATAAGTGAATTTAAGCCCTCATATATCAGCATAAACCCAAGATTTACATAAGCTAAACACGTGATAATAACCAACTAGGTTGTTTTAACCTAGATAATTGCTACATTAACAAAACTCCAACTAACACGGGCTCCGTCTTTACCCACCAACTTTCAGCATCAGTCCTACTTAATGTAGTAAGAACCGACCAACGATTTATCAGTAGGCATACTCTTATTGATGGTGAGGGGCAAATATCGTATTAGGTAACATCTCGTGAACTATTCCTGGCATTTGGTTCCTAAGTCGAGGGCTATCCTTAAGAAACCAGCCCCTGAAAGCCGAATGTTAAGCATCTGGTTAATGGTGTCAATCTTATTGTTCGTTACCCACAAAGCCGGGCGTTCTCTTATATGCATAGGGTTCTCCTTT"},
	}}

	single_id := []string{"AF298042.1"}
	out1 := Query(single_id)

	if reflect.DeepEqual(out1, AF298042) != true {
		t.Errorf("Single Query of Accession Number from NCBI did not match expected output. Received:\n %v", out1)
	}

	AF298042_AY646679 := Fasta{[]Seq{Seq{name: "AF298042.1 Salvelinus alpinus alpinus haplotype ARCTIC_16 mitochondrial D-loop, partial sequence",
		sequence: "CCACTAATATGTACAATAATGAATATTGTATCTCAACAAATTAGTGTCATAATACATCTATGTATAATATTGCATATTATGTATTTACCCATATATACAATACCTGTATGATGAGTAGTACATCATATGTATTATCAACATAAGTGAATTTAAGCCCTCATATATCAGCATAAACCCAAGATTTACATAAGCTAAACACGTGATAATAACCAACTAGGTTGTTTTAACCTAGATAATTGCTACATTAACAAAACTCCAACTAACACGGGCTCCGTCTTTACCCACCAACTTTCAGCATCAGTCCTACTTAATGTAGTAAGAACCGACCAACGATTTATCAGTAGGCATACTCTTATTGATGGTGAGGGGCAAATATCGTATTAGGTAACATCTCGTGAACTATTCCTGGCATTTGGTTCCTAAGTCGAGGGCTATCCTTAAGAAACCAGCCCCTGAAAGCCGAATGTTAAGCATCTGGTTAATGGTGTCAATCTTATTGTTCGTTACCCACAAAGCCGGGCGTTCTCTTATATGCATAGGGTTCTCCTTT"},
		Seq{name: "AY646679.1 Spironucleus barkhanus from wild Arctic charr small subunit ribosomal RNA gene, partial sequence",
			sequence: "AAGATTAAAGCCCTGCATGCCTATGTGTAGACAGTTATATTCATTATTGTGGAGCAAAAACGGCGAACAGCTCATTTATCAGTGGTAAGTGCATACAATGTATTTCGTTGGATAGTAACGGAAAATCTGTTAGTAATACATGAACTGTTTTTAGCATTATGTTAAAAATAATAGTAAGTGCGATTGTATATCTGCCACTGCAGCATCATCTTACGTTGGTGGGATATTTGCCTACCAAGGATTCGACGCTTACGGGGAATTAGGGTTTGACTCCGGAGAATGAGCATGAGAAACAGCTCATACATCTAAGGAAGGCAGCAGGCGCGGAAATTGCCCAATGTATCTTTTATACGAGGCAGTGACAAGAAATGGTAGGCACTTTTGTGCACTATCGAGGGTTAGTGGTATCTTTGCTAACCGTGACTCGTGGGCAAGCTCGGTGCCAGCAGCCGCGGTAATTCCGACACAGGGAGTTTTCCATTTGGTTGCTGCAGTTAAAAAGTTCGTAGTTTACTGACTCTTTCACTATAAGCAAAGCCGAATGCTCCAAGTTTTTTAGCAGTATTTATAGTATGAAATTATAGCGCGGCATTGAACGTAGTTTGGGGTACTCGATAGGGACAGGTGAAATAGGATGATCTATCGAAGACCCACGGTAGCGGAGGCTCCCAACGAAGTCCAAGTGTCACGATCAAGAACTAAAGTCAGGGGATAGACGACGATTAGACACCGTTTTATTCCTGACCCTAAACGATGTCGCCTAGCTGATGGGATTTTTTTCATTTGCCAAGAGAAATCGTAAGGTTTCAGACTCTGGGGGAAGTATGATCGCAAGGTTGAAACTTGAAGGGATTGACGGAGAGGTACCACCAGACGTGGAGTCTGCGGCTCAATTTGACTCAACACGCAAACATTACTAGGCCCAGAAGCTTTGAGGATTGACAGATGAGTGATCTTTCATGATTAAGTTGTTGGTGGTGCATGGCCGTTCTTAGTCCGTGATTTAAATTGTCTGCTTTATTGCGATAACGAACGAGACCTCTATCAGATTTATTATCTGAGACTGCTAGTGATGAACTAGAGGAAGGCAGAGGCAAAAACAGGTCTGTGATGCCCTTAGAAGCCCTAGGCCGCACGCGTACTACAATGGCAGGTTCATCGTGTTGCTTCCCTGAAAATGGTGGCAGTTCATTAAAACTTGTCGTGGTTAGGACTGAAGGTTGAAATTATCCTTCACGAATGAGGAATGTCTAGTAAGTGTAGGTTATGAATCTACGCTGATTACGTCCCTACCCCTTGTACACACCGCCCGTCGCTCCTACTGATTGGGAAGATCTGGTGAGTTATTCGGACCCATAGGTAAGCAATTATCTGTGGTAACAATTGCGAGCCAACTCTTCTAGAGGAAGG"},
	}}

	list_of_ids := []string{"AF298042.1", "AY646679.1"}
	out2 := Query(list_of_ids)

	if reflect.DeepEqual(out2, AF298042_AY646679) != true {
		t.Errorf("Multiple Query of Accession Number from NCBI did not match expected output. Received:\n %v", out2)
	}
}

func TestSort(t *testing.T) {

	unsorted := Fasta{entries: []Seq{Seq{name: "sdsdsd", sequence: "CAT"},
		Seq{name: "chr1", sequence: "GC"},
		Seq{name: "1chr", sequence: "ATGC"},
		Seq{name: "chr2", sequence: "AATT"}}}

	sorted := Fasta{entries: []Seq{Seq{name: "1chr", sequence: "ATGC"},
		Seq{name: "chr1", sequence: "GC"},
		Seq{name: "chr2", sequence: "AATT"},
		Seq{name: "sdsdsd", sequence: "CAT"}}}

	unsorted.Sort()
	if reflect.DeepEqual(unsorted, sorted) != true {
		t.Errorf("Sorting of Fasta structure incorrect: %v\n want: %v.", unsorted, sorted)
	}
}

func TestSummary(t *testing.T) {

	test_in := Fasta{entries: []Seq{Seq{name: "test_seq1",
		sequence: "ATGCATGCATGC"},
		Seq{name: "test_seq2",
			sequence: "ATATATATATATATATATATAAAAAGC"},
		Seq{name: "test_seq3",
			sequence: "GCGCGCGCATGCGCGCGC"},
		Seq{name: "test_seq4",
			sequence: "GGGCGGGCGGGCCC"},
	}}

	exp_output := []summaryDat{summaryDat{name: "test_seq1",
		length: 12,
		gc:     50.00},
		summaryDat{name: "test_seq2",
			length: 27,
			gc:     7.41},
		summaryDat{name: "test_seq3",
			length: 18,
			gc:     88.89},
		summaryDat{name: "test_seq4",
			length: 14,
			gc:     100.00}}

	test_output := test_in.Summary()

	test_output_string := ""
	for _, i := range test_in.Summary() {
		test_output_string = fmt.Sprintf("%v%v", test_output_string, i.String())
	}

	exp_output_string := ""
	for _, i := range test_in.Summary() {
		exp_output_string = fmt.Sprintf("%v%v", exp_output_string, i.String())
	}

	if reflect.DeepEqual(test_output_string, exp_output_string) != true {
		fmt.Printf("Summary of Fasta incorrect: %v\n want: %v.", test_output, exp_output)
	}
}
